name: Publish Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - circleci_ubuntu-20.04
          - mrchem_ubuntu-18.04
          - circleci_ubuntu-18.04
          - circleci_ubuntu-18.04-conda

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
